In [3]:
import pandas as pd
import numpy as np

In [14]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'gender': ['F', 'M', 'M', 'M'],
    'nationality':['USA', 'UK', 'USA', 'UK'],
    'city':['London','London', 'London', 'London'],
    'height': [180, 195, 175, 180],
}
df = pd.DataFrame(data)
df

      name  age gender nationality    city  height
0    Alice   25      F         USA  London     180
1      Bob   30      M          UK  London     195
2  Charlie   35      M         USA  London     175
3    David   40      M          UK  London     180

In [5]:
df.info

<bound method DataFrame.info of       name age gender nationality
0    Alice  25      F         USA
1      Bob  30      M          UK
2  Charlie  35      M         USA
3    David  40      M          UK>

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         4 non-null      str
 1   age          4 non-null      int64
 2   gender       4 non-null      str
 3   nationality  4 non-null      str
 4   city         4 non-null      str
dtypes: int64(1), str(4)
memory usage: 292.0 bytes

In [15]:
df.shape

(4, 6)

In [16]:
df.describe().T

        count   mean       std    min     25%    50%     75%    max
age       4.0   32.5  6.454972   25.0   28.75   32.5   36.25   40.0
height    4.0  182.5  8.660254  175.0  178.75  180.0  183.75  195.0

This is a comment

In [18]:
v = pd.read_csv("/home/adamson/Downloads/housing_price_dataset.csv")
v

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [19]:
v.head()

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [20]:
v.head(5)

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [21]:
v.head(25)

    SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0         2126         4          1        Rural       1969  215355.283618
1         2459         3          2        Rural       1980  195014.221626
2         1860         2          1       Suburb       1970  306891.012076
3         2294         2          1        Urban       1996  206786.787153
4         2130         5          2       Suburb       2001  272436.239065
5         2095         2          3       Suburb       2020  198208.803907
6         2724         2          1       Suburb       1993  343429.319110
7         2044         4          3        Rural       1957  184992.321268
8         2638         4          3        Urban       1959  377998.588152
9         1121         5          2        Urban       2004   95961.926014
10        1466         5          3       Suburb       1951  191113.768679
11        2238         3          3       Suburb       1987  253358.645002
12        1330         2          2       Suburb       1992  132172.392617
13        2482         4          3       Suburb       1989  231157.027676
14        1087         4          1        Urban       1976  118393.823163
15        2396         2          2       Suburb       1993  267377.399686
16        2123         5          2        Rural       1956  190773.148563
17        1871         4          2       Suburb       1977  172989.804901
18        2687         5          1        Urban       1979  239222.667797
19        1130         4          3        Rural       1962  143050.201782
20        2685         4          3        Urban       1999  405523.828317
21        2332         3          3        Rural       1978  263954.154063
22        1769         4          1       Suburb       1963  148310.620168
23        1343         2          3        Rural       2013  151733.922490
24        2515         2          3        Urban       2013  307961.107382

In [22]:
v.tail()

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

In [23]:
v.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SquareFeet    50000 non-null  int64
 1   Bedrooms      50000 non-null  int64
 2   Bathrooms     50000 non-null  int64
 3   Neighborhood  50000 non-null  str
 4   YearBuilt     50000 non-null  int64
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 2.3 MB

There are three data types, (integer, float, string). Thereare 50,000 entries.

In [24]:
v.shape

(50000, 6)

There are 50000 rows and 6 columns

In [25]:
v.describe().T

,count,mean,std,min,25%,50%,75%,max
SquareFeet,50000.0,2006.374680,575.513241,1000.000000,1513.000000,2007.000000,2506.000000,2999.000000
Bedrooms,50000.0,3.498700,1.116326,2.000000,3.000000,3.000000,4.000000,5.000000
Bathrooms,50000.0,1.995420,0.815851,1.000000,1.000000,2.000000,3.000000,3.000000
YearBuilt,50000.0,1985.404420,20.719377,1950.000000,1967.000000,1985.000000,2003.000000,2021.000000
Price,50000.0,224827.325151,76141.842966,-36588.165397,169955.860225,225052.141166,279373.630052,492195.259972

In [27]:
v["Bedrooms"]

0        4
1        3
2        2
3        2
4        5
        ..
49995    5
49996    2
49997    5
49998    5
49999    5
Name: Bedrooms, Length: 50000, dtype: int64

In [30]:
v[["Bedrooms","Bathrooms"]]

       Bedrooms  Bathrooms
0             4          1
1             3          2
2             2          1
3             2          1
4             5          2
...         ...        ...
49995         5          3
49996         2          2
49997         5          3
49998         5          2
49999         5          3

[50000 rows x 2 columns]

In [31]:
v[["Bedrooms","Bathrooms"]].head

<bound method NDFrame.head of        Bedrooms  Bathrooms
0             4          1
1             3          2
2             2          1
3             2          1
4             5          2
...         ...        ...
49995         5          3
49996         2          2
49997         5          3
49998         5          2
49999         5          3

[50000 rows x 2 columns]>

In [32]:
v[["Bedrooms","Bathrooms"]].head(10)

   Bedrooms  Bathrooms
0         4          1
1         3          2
2         2          1
3         2          1
4         5          2
5         2          3
6         2          1
7         4          3
8         4          3
9         5          2

In [37]:
v[3:9:]

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065
5        2095         2          3       Suburb       2020  198208.803907
6        2724         2          1       Suburb       1993  343429.319110
7        2044         4          3        Rural       1957  184992.321268
8        2638         4          3        Urban       1959  377998.588152

In [41]:
v.loc[0:3,:]

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153

In [42]:
v.loc[0:8,"Bedrooms"]

0    4
1    3
2    2
3    2
4    5
5    2
6    2
7    4
8    4
Name: Bedrooms, dtype: int64

In [45]:
v.iloc[0:8,2:3]

   Bathrooms
0          1
1          2
2          1
3          1
4          2
5          3
6          1
7          3

In [47]:
v.iloc[0:8,2:6]

   Bathrooms Neighborhood  YearBuilt          Price
0          1        Rural       1969  215355.283618
1          2        Rural       1980  195014.221626
2          1       Suburb       1970  306891.012076
3          1        Urban       1996  206786.787153
4          2       Suburb       2001  272436.239065
5          3       Suburb       2020  198208.803907
6          1       Suburb       1993  343429.319110
7          3        Rural       1957  184992.321268

In [52]:
v[v['Price'] > 225000]

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
2            1860         2          1       Suburb       1970  306891.012076
4            2130         5          2       Suburb       2001  272436.239065
6            2724         2          1       Suburb       1993  343429.319110
8            2638         4          3        Urban       1959  377998.588152
11           2238         3          3       Suburb       1987  253358.645002
...           ...       ...        ...          ...        ...            ...
49990        2724         5          2       Suburb       1978  395026.724290
49994        2426         5          2        Urban       1950  331497.091307
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957

[25016 rows x 6 columns]

In [53]:
v[v['Price'] > 225000].head()

    SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
2         1860         2          1       Suburb       1970  306891.012076
4         2130         5          2       Suburb       2001  272436.239065
6         2724         2          1       Suburb       1993  343429.319110
8         2638         4          3        Urban       1959  377998.588152
11        2238         3          3       Suburb       1987  253358.645002

In [56]:
v.query('Price>225000')

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
2            1860         2          1       Suburb       1970  306891.012076
4            2130         5          2       Suburb       2001  272436.239065
6            2724         2          1       Suburb       1993  343429.319110
8            2638         4          3        Urban       1959  377998.588152
11           2238         3          3       Suburb       1987  253358.645002
...           ...       ...        ...          ...        ...            ...
49990        2724         5          2       Suburb       1978  395026.724290
49994        2426         5          2        Urban       1950  331497.091307
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957

[25016 rows x 6 columns]

In [57]:
v.query('Price>225000').head()

    SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
2         1860         2          1       Suburb       1970  306891.012076
4         2130         5          2       Suburb       2001  272436.239065
6         2724         2          1       Suburb       1993  343429.319110
8         2638         4          3        Urban       1959  377998.588152
11        2238         3          3       Suburb       1987  253358.645002

In [59]:
v.groupby('Bathrooms')['Price']

In [66]:
price_by_neighborhood = v.groupby('Neighborhood')['Price']
pd.DataFrame(price_by_neighborhood)

        0                                                  1
0   Rural  0        215355.283618
1        195014.221626
...
1  Suburb  2        306891.012076
4        272436.239065
...
2   Urban  3        206786.787153
8        377998.588152
...

In [71]:
v['Neighborhood'].value_counts()

Neighborhood
Suburb    16721
Rural     16676
Urban     16603
Name: count, dtype: int64

In [78]:
# v.groupby(['Neighborhood','Price'])
pd.DataFrame(v.groupby(['Neighborhood','Price']))

,0,1
0,"(Rural, -28774.99802220965)",SquareFeet Bedrooms Bathrooms Neighbo...
1,"(Rural, -19871.251145635964)",SquareFeet Bedrooms Bathrooms Neighbor...
2,"(Rural, -18159.685676249966)",SquareFeet Bedrooms Bathrooms Neighbo...
3,"(Rural, -13803.68405898445)",SquareFeet Bedrooms Bathrooms Neighbor...
4,"(Rural, -8238.884498829517)",SquareFeet Bedrooms Bathrooms Neighbo...
...,...,...
49995,"(Urban, 467492.8278233021)",SquareFeet Bedrooms Bathrooms Neighbo...
49996,"(Urban, 468470.3780038055)",SquareFeet Bedrooms Bathrooms Neighbo...
49997,"(Urban, 468493.8778409183)",SquareFeet Bedrooms Bathrooms Neighbo...
49998,"(Urban, 470989.6790739138)",SquareFeet Bedrooms Bathrooms Neighbor...
49999,"(Urban, 476671.7332626706)",SquareFeet Bedrooms Bathrooms Neighbo...